services:
  modernlinux:
    build: .
    container_name: linux-network-namespace
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./scripts:/scripts
      - ./tmp/http-home:/tmp/http-home
    command: bash   
